name: Build and Package EXE

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile src/main.py `
          --windowed `
          -i "NONE" `
          --add-data "src/haarcascade_frontalface_default.xml;cv2/data" `
          --add-data "src/shape_predictor_68_face_landmarks.dat;src" 

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: biometrisches-passbild-tool
        path: dist/main.exe
